name: dart_playground
description: A sample command line application

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-85.0.dev <3.0.0'


dependencies:
  dio: ^4.0.6
  http: ^0.13.4
  uno: ^1.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0